### ISSUE TITLE
python model.py weights/ "hello world!" ... weights?

### ISSUE THREAD

**Issue by that-scientist** [j-csc/mlx_bark#5]
Looking at your documentation, at least on my macbook in a conda environment, the line to run doesn't look right.

```
python model.py weights/ "hello world!"
```

Terminal just shows dquote> ... presumably the exclamation mark is the issue there.

by contrast, running this at least gets me to coarse token death:

`python model.py --text "hello world"`

So, what's this weights/ ?

**Comment by j-csc** [comment]
Apologies if the docs were unclear. weights/ is supposed to be the directory where you downloaded the weights to

**Comment by j-csc** [comment]
See https://github.com/j-csc/mlx_bark/issues/4 if it solves your issues
